### ISSUE TITLE
ValueError: Cannot iterate over a shape with unknown rank.

### ISSUE THREAD

**Issue by lmg1999** [bubbliiiing/mask-rcnn-keras#12]
Traceback (most recent call last):
  File "train.py", line 124, in <module>
    loss=[None] * len(model.outputs)
  File "/root/miniconda3/lib/python3.7/site-packages/keras/engine/training.py", line 211, in compile
    self._cache_output_metric_attributes(metrics, weighted_metrics)
  File "/root/miniconda3/lib/python3.7/site-packages/keras/engine/training.py", line 736, in _cache_output_metric_attributes
    output_shapes.append(list(output.shape))
  File "/root/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 838, in __iter__
    raise ValueError("Cannot iterate over a shape with unknown rank.")
ValueError: Cannot iterate over a shape with unknown rank.

这是什么原因呢？没办法解决

**Comment by bubbliiiing** [comment]
一般不是版本问题就是数据集问题诶。

**Comment by dianyuan9527** [comment]
老哥你解决了吗？我也遇到了

**Comment by iiiicode** [comment]
我也遇到了这个问题，没有解决

**Comment by lmg1999** [comment]
是版本问题&nbsp; 我按照要求更新了对应版本 就可以了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bubbliiiing/mask-rcnn-keras"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月24日(星期一) 晚上9:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bubbliiiing/mask-rcnn-keras] ValueError: Cannot iterate over a shape with unknown rank. (#12)





 
我也遇到了这个问题，没有解决

**Comment by iiiicode** [comment]
我是按照他的要求安装的，为啥还报错了啊





------------------ Original ------------------
From: lmg1999 ***@***.***&gt;
Date: Mon,May 24,2021 9:27 PM
To: bubbliiiing/mask-rcnn-keras ***@***.***&gt;
Cc: iiiicode ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [bubbliiiing/mask-rcnn-keras] ValueError: Cannot iterate over a shape with unknown rank. (#12)

**Comment by bubbliiiing** [comment]
0 0你们都是啥版本

**Comment by Jay-10-yao** [comment]
我也遇到这个问题了，目前版本是keras=2.3.1， tensorflow=1.13.1

**Comment by iiiicode** [comment]
> 我也遇到这个问题了，目前版本是keras=2.3.1， tensorflow=1.13.1

你看看是不是你的数据集有问题

**Comment by Jay-10-yao** [comment]
> > 我也遇到这个问题了，目前版本是keras=2.3.1， tensorflow=1.13.1
> 
> 你看看是不是你的数据集有问题

用的是原来那个shape的数据集

**Comment by bubbliiiing** [comment]
可能2.1.5好一些

**Comment by Jay-10-yao** [comment]
> 可能2.1.5好一些

我直接运行conda install tensorflow==1.13.1
conda install keras==2.1.5
结果装keras报了一堆confilct

**Comment by Jay-10-yao** [comment]
> 可能2.1.5好一些

我直接运行conda install tensorflow=1.13.1
conda install keras=2.1.5
结果装keras报了一堆confilct

**Comment by Jay-10-yao** [comment]
> 可能2.1.5好一些

我直接建了一个新环境，python=3.6
然后运行conda install tensorflow==1.13.1
conda install keras==2.1.5
结果装keras报了一堆confilct

**Comment by bubbliiiing** [comment]
按照教程的话一般是先激活环境，然后用pip装，不是用conda装
