### ISSUE TITLE
训练coco数据集过程中，Exception: Invalid bounding box with area of zero，请问您知道怎么解决嘛

### ISSUE THREAD

**Issue by KevinR10** [bubbliiiing/mask-rcnn-keras#29]
561/58633 [..............................] - ETA: 6:54:06 - loss: 1.6840 - rpn_class_loss_loss: 0.1094 - rpn_bbox_loss_loss: 0.8315 - mrcnn_class_loss_loss: 0.1723 - mrcnn_bbox_loss_loss: 0.2518 - mrcnn_mask_loss_loss: 0.3191Traceback (most recent call last):
  File "train.py", line 299, in <module>
    callbacks=callbacks
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/data_utils.py", line 601, in get
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/data_utils.py", line 595, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/opt/data/private/Kevin/mask-rcnn-keras/utils/dataloader.py", line 250, in __getitem__
    load_image_gt(image, mask_gt, boxes, class_ids, image_id, self.config, use_mini_mask=self.config.USE_MINI_MASK)
  File "/opt/data/private/Kevin/mask-rcnn-keras/utils/dataloader.py", line 59, in load_image_gt
    mask = minimize_mask(boxes, mask, config.MINI_MASK_SHAPE)
  File "/opt/data/private/Kevin/mask-rcnn-keras/utils/dataloader.py", line 24, in minimize_mask
    raise Exception("Invalid bounding box with area of zero")
Exception: Invalid bounding box with area of zero

**Comment by bubbliiiing** [comment]
你的标签里面有宽高为0的情况？

**Comment by KevinR10** [comment]
> 你的标签里面有宽高为0的情况？

应该没有啊，就用的是coco2017数据集，没改数据集的内容

**Comment by KevinR10** [comment]
>



> 是我刚提供的代码吗……如果是的话我加个错误判断

应该是，我看代码文件的修改日期是‎2022‎年‎5‎月‎4‎日，‏‎20:40:07

**Comment by bubbliiiing** [comment]
好的，那我加一个看看…，但是你训练coco，也太久了吧，我没试过coco的效果

**Comment by bubbliiiing** [comment]
啊不是说你速度有问题，只是单纯感叹用训练coco这件事而已，数据太多，2080ti根本不够用

**Comment by KevinR10** [comment]
> 

确实是，哈哈哈感谢回复

**Comment by KevinR10** [comment]
> 啊不是说你速度有问题，只是单纯感叹用训练coco这件事而已，数据太多，2080ti根本不够用

确实是，哈哈哈感谢回复
