### ISSUE TITLE
ValueError: **slice index -1 of dimension 0 out of bounds.** for '{{node loss/rpn_class_loss_loss/strided_slice}} = 

### ISSUE THREAD

**Issue by immaping** [bubbliiiing/mask-rcnn-keras#42]
Traceback (most recent call last):
  File "E:/relate_code/mask-rcnn-keras-master/train.py", line 237, in <module>
    **'mrcnn_mask_loss'   : lambda y_true, y_pred: y_pred**
  File "C:\Anaconda3\envs\mask_rcnn_keras\lib\site-packages\tensorflow\python\trackable\base.py", line 205, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Anaconda3\envs\mask_rcnn_keras\lib\site-packages\keras\engine\training_v1.py", line 497, in compile
    self._compile_weights_loss_and_weighted_metrics()
  File "C:\Anaconda3\envs\mask_rcnn_keras\lib\site-packages\tensorflow\python\trackable\base.py", line 205, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Anaconda3\envs\mask_rcnn_keras\lib\site-packages\keras\engine\training_v1.py", line 1696, in _compile_weights_loss_and_weighted_metrics
    self.total_loss = self._prepare_total_loss(masks)
  File "C:\Anaconda3\envs\mask_rcnn_keras\lib\site-packages\keras\engine\training_v1.py", line 1763, in _prepare_total_loss
    per_sample_losses = loss_fn.call(y_true, y_pred)
  File "C:\Anaconda3\envs\mask_rcnn_keras\lib\site-packages\keras\losses.py", line 266, in call
    y_pred, y_true
  File "C:\Anaconda3\envs\mask_rcnn_keras\lib\site-packages\keras\utils\losses_utils.py", line 205, in squeeze_or_expand_dimensions
    is_last_dim_1 = tf.equal(1, tf.shape(y_pred)[-1])
  File "C:\Anaconda3\envs\mask_rcnn_keras\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Anaconda3\envs\mask_rcnn_keras\lib\site-packages\tensorflow\python\framework\ops.py", line 1969, in _create_c_op
    raise ValueError(e.message)
# #ValueError: **slice index -1 of dimension 0 out of bounds.** for '{{node loss/rpn_class_loss_loss/strided_slice}} = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1](loss/rpn_class_loss_loss/Shape, loss/rpn_class_loss_loss/strided_slice/stack, loss/rpn_class_loss_loss/strided_slice/stack_1, loss/rpn_class_loss_loss/strided_slice/stack_2)' with input shapes: [0], [1], [1], [1] and with computed input tensors: input[1] = <-1>, input[2] = <0>, input[3] = <1>.
用的tensorflow2.10版本，说模型编译这里出错，这个bug该怎么改啊？感觉挺对的啊 #

**Comment by bubbliiiing** [comment]
2.10貌似高了些……
