### ISSUE TITLE
测试的时候出现IndexError: list index out of range

### ISSUE THREAD

**Issue by pengfeichu1992** [bubbliiiing/mask-rcnn-keras#45]
大佬 这个该这么解决。。
> Configurations:
> BACKBONE_STRIDES               [4, 8, 16, 32, 64]
> BATCH_SIZE                     0
> BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
> DETECTION_MAX_INSTANCES        100
> DETECTION_MIN_CONFIDENCE       0.05
> DETECTION_NMS_THRESHOLD        0.5
> FPN_CLASSIF_FC_LAYERS_SIZE     1024
> GPU_COUNT                      0
> IMAGES_PER_GPU                 1
> IMAGE_MAX_DIM                  512
> IMAGE_META_SIZE                93
> IMAGE_SHAPE                    [512 512   3]
> LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 1.0}
> MASK_POOL_SIZE                 14
> MASK_SHAPE                     [28, 28]
> MAX_GT_INSTANCES               100
> MINI_MASK_SHAPE                (56, 56)
> NUM_CLASSES                    81
> POOL_SIZE                      7
> POST_NMS_ROIS_INFERENCE        1000
> POST_NMS_ROIS_TRAINING         2000
> PRE_NMS_LIMIT                  6000
> ROI_POSITIVE_RATIO             0.33
> RPN_ANCHOR_RATIOS              [0.5, 1, 2]
> RPN_ANCHOR_SCALES              [32, 64, 128, 256, 512]
> RPN_ANCHOR_STRIDE              1
> RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
> RPN_NMS_THRESHOLD              0.7
> RPN_TRAIN_ANCHORS_PER_IMAGE    256
> TOP_DOWN_PYRAMID_SIZE          256
> TRAIN_BN                       False
> TRAIN_ROIS_PER_IMAGE           200
> USE_MINI_MASK                  True
> 
> 
> WARNING:tensorflow:From /cloud/mrcnn_tf1.13.1/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Colocations handled automatically by placer.
> WARNING:tensorflow:From /home/featurize/work/mask-rcnn-keras/nets/layers.py:386: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.cast instead.
> 2023-03-02 03:28:03.316527: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2023-03-02 03:28:03.321351: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2399995000 Hz
> 2023-03-02 03:28:03.321625: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x558ec6a395f0 executing computations on platform Host. Devices:
> 2023-03-02 03:28:03.321648: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
> Load model done.
> Get predict result.
> 0it [00:00, ?it/s]
> 
> Json files dumped, saved in: 'eval_results/', start evaluting.
> Loading and preparing results...
> Traceback (most recent call last):
>   File "eval-Copy1.py", line 71, in <module>
>     bbox_dets = test_coco.loadRes(osp.join(map_out_path, "bbox_detections.json"))
>   File "/cloud/mrcnn_tf1.13.1/lib/python3.6/site-packages/pycocotools/coco.py", line 329, in loadRes
>     if 'caption' in anns[0]:
> IndexError: list index out of range

**Comment by pengfeichu1992** [comment]
我的测试数据集是 官网的test2017

**Comment by pengfeichu1992** [comment]
知道了 只用预训练权重去测试就会有这个问题，训练后测试就ok
